### PR TITLE
Generalized identifier validation

### LINKED ISSUE #152: [BUG] Invalid Syntax Accepted for Generalized Identifiers
**Expected behavior**
generalized-identifiers of "a{new line character}b" and "a/*hi*/b" should be rejected because they don't comply with the [appropriate syntax rules](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#identifiers) in the Power Query language specification.

**Actual behavior**
Both of the above identifiers are accepted as valid.

**To Reproduce**
````
const customParser: IParser<IParserState> = {
    ...RecursiveDescentParser,
    read: RecursiveDescentParser.readGeneralizedIdentifier,
};
const customSettings: Settings = {
    ...DefaultSettings,
    parser: customParser,
};
const triedLexParse: Task.TriedLexParse = Task.tryLexParse(
    customSettings,
    `a
b`
    // or 'a/*hi*/b'
); // expect the result to be an error; currently, an ok result is being returned
````

**Additional context**
If I'm understanding the language specification correctly, a `generalized-identifier` is made up of one or more (`keyword-or-identifier` or decimal-digit + `keyword-or-identifier`) segments, separated by dots (.) or blanks (e.g. spaces). 

In turn, the only characters allowed in `keyword-or-identifier` are letters, numbers and underscores plus connecting, combining and formatting characters. Turning this list into a regular expression (using the specific character classes listed in the spec) produces the following: `[\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Mn}\p{Mc}\p{Pc}\p{Cf}\p{Nd}_]`

`\n`, `/` and `*` all do not match this regex so I believe should be rejected as invalid `generalized-identifier` syntax.

(Note: The above regex tests valid characters allowed in a `keyword-or-identifier`; however, for simplicity, it does not check whether the identifier's starting character matches the rules for the starting character given in the spec.

### PR DESCRIPTION
**Pull request by JordanBoltonMN**
Should resolve #152

### CODE REVIEW

File: src/test/libraryTest/utils/stringUtils.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+import "mocha";
+import { StringUtils } from "../../../common";
+
+describe("StringUtils", () => {
+    describe(`isGeneralizedIdentifier`, () => {
+        it("a", () => expect(StringUtils.isGeneralizedIdentifier("a"), "should be true").to.be.true);
+        it("a.1", () => expect(StringUtils.isGeneralizedIdentifier("a.1"), "should be true").to.be.true);
+        it("a b", () => expect(StringUtils.isGeneralizedIdentifier("a b"), "should be true").to.be.true);
+
+        it("a..1", () => expect(StringUtils.isGeneralizedIdentifier("a..1"), "should be true").to.be.false);
```
Comment (mattmasson) [inline src/test/libraryTest/utils/stringUtils.ts:14]: nit: false
